sudo: false
language: ruby
rvm:
  - 2.3.0
before_script:
  - mkdir ~/.yard
  - bundle exec yard config load_plugins true
  - export DISPLAY=:99
  - sh -e /etc/init.d/xvfb start
  - support/travis.sh
  - export PATH="$(pwd)/bin:$PATH"
